src/Game.js, src/Log.js, src/LogItem.js, src/MainSidebar.js, src/Plague.js, src/UtilityFunctions.js, src/Views/MainGame.js, src/Views/MenuScreen.js
Added ability to start infection, and log it to a log.
=> Infection start

src/Game.js, src/Log.js, src/LogItem.js, src/UtilityFunctions.js, src/Views/MainGame.js
This set of commits changes how the game first starts off.
A simple set of `setTimeout()`'s is used to initiate a cascade when the `<MainGame>` component is mounted to the DOM.
1. Start message is logged.
2. Patient Zero is infected.
3. Decide to infect interval is set.
=> Fixes Patient Zero Logic

src/StartMenuForm.js
Created simple validation that sets the buttons to "disabled" if there is no input.
=> Fixes Issue #18

src/Game.js, src/Log.js, src/Views/MainGame.js, src/style.css
Adds a button to clear the Game Log.
=> Fix issue #19 - Add ability to clear Game Log

src/Game.js, src/Skip.js, src/UtilityFunctions.js, src/style.css
The Skip button only appears on the StartScreen view. When clicked, it will set the player's morality to 'evil', name to 'Black Death', classType to 'Plague', and className to 'Bubonic'.
It will then show the MainGame screen.
Fixes Issue #22.
=> Created a Skip Button

src/LogItem.js
Slightly slower fade in for Log Items.
Issue #27
=> Makes LogItems fade in slightly slower.

src/MainSidebar.js
When the SideBar is loaded, an icon of the class will appear in the header.
Issue #28.
=> Added Class Icons to MainSidebar

coming-soon/docs/style.css
=> Smaller coverpage image.

coming-soon/docs/randomImage.js
Previously, there was no return value
Issue #39
=> Fixes isTheSame()

package-lock.json, src/components/Log.js, src/components/LogItem.js, src/components/PlagueLogic.js, src/redux/actions/actions.js, src/redux/reducers/reducers.js, src/screens/home.js
=> ✨ 4. Game Log

package-lock.json, package.json, src/components/Log.js, src/components/LogItem.js, src/tests/components/Log.test.js, src/tests/components/LogItem.test.js, src/tests/components/Sidebar.test.js, src/tests/components/SidebarData.test.js, src/tests/components/Tag.test.js, src/tests/components/__snapshots__/Log.test.js.snap, src/tests/components/__snapshots__/LogItem.test.js.snap, src/tests/components/__snapshots__/Sidebar.test.js.snap, src/tests/components/__snapshots__/SidebarData.test.js.snap, src/tests/components/__snapshots__/Tag.test.js.snap, src/tests/fixtures/developmentState.js, src/tests/fixtures/log.js, src/tests/screens/ChooseMorality.test.js, src/tests/screens/ChooseName.test.js, src/tests/screens/ChooseType.test.js, src/tests/screens/Home.test.js, src/tests/screens/__snapshots__/ChooseMorality.test.js.snap, src/tests/screens/__snapshots__/ChooseName.test.js.snap, src/tests/screens/__snapshots__/ChooseType.test.js.snap, src/tests/screens/__snapshots__/Home.test.js.snap
Write snapshot tests for components and screens.
=> ✅ 5. Snapshot Tests

src/components/Sidebar.js, src/tests/components/__snapshots__/Sidebar.test.js.snap, src/tests/screens/__snapshots__/Home.test.js.snap
Change Sidebar padding from `large` to `small`.
=> ✏️ 7 - Sidebar Padding

.travis.yml, src/components/Log.js, src/components/LogItem.js, src/components/Sidebar.js, src/components/SidebarData.js, src/components/Tag.js, src/screens/chooseMorality.js, src/screens/chooseName.js, src/screens/chooseType.js, src/screens/home.js, src/tests/components/Log.test.js, src/tests/components/LogItem.test.js, src/tests/components/Sidebar.test.js, src/tests/components/SidebarData.test.js, src/tests/components/Tag.test.js, src/tests/components/__snapshots__/Log.test.js.snap, src/tests/components/__snapshots__/Sidebar.test.js.snap, src/tests/screens/ChooseMorality.test.js, src/tests/screens/ChooseName.test.js, src/tests/screens/ChooseType.test.js, src/tests/screens/Home.test.js, src/tests/screens/__snapshots__/ChooseMorality.test.js.snap, src/tests/screens/__snapshots__/ChooseName.test.js.snap, src/tests/screens/__snapshots__/ChooseType.test.js.snap, src/tests/screens/__snapshots__/Home.test.js.snap
Uses Travis CI for Continuous Integration. Modified test files for shallow/non-shallow rendering depending on component.
=> 🚀 10 - Continuous Integration

.travis.yml, src/constants.js
Somehow the file names in /screens are becoming lowercase.
=> ✏️ Attempt to Fix Travis CI Failing

src/components/Log.js, src/components/Sidebar.js, src/constants.js, src/screens/ChooseMorality.js, src/screens/ChooseName.js, src/screens/ChooseType.js, src/screens/Home.js, src/tests/components/Log.test.js, src/tests/components/Sidebar.test.js, src/tests/components/__snapshots__/Log.test.js.snap, src/tests/screens/ChooseMorality.test.js, src/tests/screens/ChooseName.test.js, src/tests/screens/ChooseType.test.js, src/tests/screens/Home.test.js
Adds propTypes to all components. Better error catching.
=> ✏️ 11 - PropTypes

.travis.yml, src/components/PlagueLogic.js
Adds `cache` and `build` to Travis config. Also tweaks the PlagueLogic component so that it returns `null`, and removes the `React` import.
=> ✏️ 12 - Travis Config

README.md
Update README to include Travis CI Build tag.
=> ✏️ 13 - Travis CI Tag

package.json
Adds a `publish` npm script to run `np` and then `github_changelog_generator`.
=> ✏️ 14 - GitHub Changelog Generator Command

src/components/PlagueLogic.js
Will no longer be able to infect more than the healthy population. Will stop running the infection interval function once there is no more healthy population.
=> ✏️ 16 - Edit Infection Max

src/components/Navbar.js, src/screens/Home.js, src/tests/components/Navbar.test.js, src/tests/components/__snapshots__/Navbar.test.js.snap, src/tests/screens/__snapshots__/Home.test.js.snap
=> ✨ 21 - Navbar

README.md, package-lock.json, package.json
Adds support for codecov Code Coverage.
=> ✅ 23 - Code Coverage

package-lock.json, package.json
=> 📦 24 - Webpack Dev Server

package-lock.json, package.json, src/constants.js, src/screens/ChooseName.js, src/tests/screens/ChooseName.test.js, src/tests/screens/__snapshots__/ChooseName.test.js.snap
Adds ability to click a button to choose a random name on the ChooseName screen.
Issue #11
=> ✨ 27 - Randomize Name

src/screens/ChooseMorality.js, src/screens/ChooseName.js, src/screens/ChooseType.js, src/tests/screens/__snapshots__/ChooseMorality.test.js.snap, src/tests/screens/__snapshots__/ChooseName.test.js.snap, src/tests/screens/__snapshots__/ChooseType.test.js.snap
Add the new `<Form />` component from Grommet in v2. This fixes issue with `ChooseName` screen submitting the whole form when user presses enter on keyboard.
=> ✏️ 28 - Grommet Form

package-lock.json, package.json, src/components/Log.js, src/components/LogItem.js, src/tests/components/__snapshots__/Log.test.js.snap, src/tests/components/__snapshots__/LogItem.test.js.snap
Updates `<Log />` UI to look better.
=> 🎨 29 - Update Log UI

src/index.js, src/style.css
Adds Comfortaa font from Google Fonts.
=> ✏️ 33 - Comfortaa
